site_name: EVRGStudy
site_url: https://EliasVRG.github.io/EVRGStudy/
site_dir: _site  # Verifique se isso está correto
site_author: Elias Victor Rocha Garcia
site_description: Essa documentação foi criada com o objetivo de auxiliar os iniciantes na utilização de diferentes recursos que tive experiência no meu dia a dia.

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: black
    accent: 'light blue'
  icon:
    logo: 'material/library'
    repo: 'fontawesome/brands/github'
  features:
    - navigation.tabs
    - toc.integrate
  language: 'en'

# Seção de navegação personalizada
nav:
  - Home: index.md
  - GitHub: https://github.com/EliasVRG
