name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Altere para o nome do branch principal onde o código é desenvolvido
  workflow_dispatch:  # Permite disparar o workflow manualmente

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que todo o histórico do repositório seja baixado

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Substitua por uma versão específica, se necessário

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build --site-dir ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
